### ISSUE TITLE
AttributeError: 'str' object has no attribute 'astimezone'

### ISSUE THREAD

**Issue by MortezaMohebi** [mrr-r/convert-date-on-reports-pdf-in-odoo-to-jalali#1]
both modules installed successfully , but when i want to print a new report this error will appear:

str' object has no attribute 'astimezone'
Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 347, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_sale_report_saleorder_document_17114
  File "<template>", line 2, in body_call_content_17113
  File "/opt/odoo/odoo11-custom-addons/sale_jalali_date/model/sale_jalali_date_printout.py", line 13, in convert_jalali
    return convert_jalali_wt(obj.date_order)
  File "/opt/odoo/odoo11-custom-addons/base_jalali_convert/convert_jalali.py", line 24, in convert_jalali_wt
    original_date_i = original_date.astimezone(iran)
AttributeError: 'str' object has no attribute 'astimezone'

Error to render compiling AST
AttributeError: 'str' object has no attribute 'astimezone'
Template: sale.report_saleorder_document
Path: /templates/t/t/div/div[3]/div[3]/p
Node: <p t-esc="doc.convert_jalali(doc)"/>

**Comment by mrr-r** [comment]
این ماژول برای اودوو 14 درست کار می کند و برای اودووهای دیگر باید ماژول های دیگر طراحی شود.
اینطور که به نظر می آد شما از اودووی 11 استفاده می کنید.

**Comment by mrr-r** [comment]
> both modules installed successfully , but when i want to print a new report this error will appear:
> 
> str' object has no attribute 'astimezone' Traceback (most recent call last): File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 347, in _compiled_fn return compiled(self, append, new, options, log) File "", line 1, in template_sale_report_saleorder_document_17114 File "", line 2, in body_call_content_17113 File "/opt/odoo/odoo11-custom-addons/sale_jalali_date/model/sale_jalali_date_printout.py", line 13, in convert_jalali return convert_jalali_wt(obj.date_order) File "/opt/odoo/odoo11-custom-addons/base_jalali_convert/convert_jalali.py", line 24, in convert_jalali_wt original_date_i = original_date.astimezone(iran) AttributeError: 'str' object has no attribute 'astimezone'
> 
> Error to render compiling AST AttributeError: 'str' object has no attribute 'astimezone' Template: sale.report_saleorder_document Path: /templates/t/t/div/div[3]/div[3]/p Node:

این ماژول برای اودوو 14 درست کار می کند و برای اودووهای دیگر باید ماژول های دیگر طراحی شود.
اینطور که به نظر می آد شما از اودووی 11 استفاده می کنید.
